@php
    $assistantName = ai_assistant_name();
@endphp
<script>
    window.GeminiAssistantConfig = {
        mode: @json($mode ?? 'widget'),
        defaultOpen: @json(($mode ?? 'widget') !== 'page'),
        assistantName: @json($assistantName),
        chatUrl: @json(route('ai.assistant.chat')),
        liveTokenUrl: @json(route('ai.assistant.live-token')),
            labels: {
                welcome: @json(get_phrase('Hello! I am') . ' ' . $assistantName . '. ' . get_phrase('Share your screen on the right, then ask me anything — I see your screen live with each message.')),
                ready: @json(get_phrase('Ready to help')),
            thinking: @json(get_phrase('Analyzing your screen...')),
            liveActive: @json(get_phrase('Live sharing active')),
            screenActive: @json(get_phrase('Screen sharing live')),
            liveOff: @json(get_phrase('Live screen sharing')),
            liveFrame: @json(get_phrase('Live frame will be sent with your message')),
            screenFrame: @json(get_phrase('Current screen frame will be sent with your message')),
            snapshotFrame: @json(get_phrase('Snapshot attached to next message')),
            screenStarted: @json(get_phrase('Screen sharing is live. Ask your question or click Analyze screen.')),
            cameraStarted: @json(get_phrase('Camera is live. Ask your question.')),
            screenStopped: @json(get_phrase('Screen sharing stopped.')),
            screenHint: @json(get_phrase('Click Share screen to start live screen sharing first.')),
            analyzePrompt: @json(get_phrase('Analyze my current screen and tell me what you see. Help me with anything visible on screen.')),
            live: @json(get_phrase('LIVE')),
            liveScreen: @json(get_phrase('SCREEN LIVE')),
            liveCamera: @json(get_phrase('CAMERA LIVE')),
            listening: @json(get_phrase('Listening...')),
            voiceModeOn: @json(get_phrase('Voice mode enabled. Speak naturally, I will answer by voice.')),
            voiceModeOff: @json(get_phrase('Voice mode disabled.')),
            liveVoiceStart: @json(get_phrase('Start live voice assistant')),
            liveVoiceConnecting: @json(get_phrase('Connecting to voice assistant...')),
            liveVoiceListening: @json(get_phrase('Speak now — I am listening in real time.')),
            liveVoiceSpeaking: @json($assistantName . ' ' . get_phrase('is speaking...')),
            liveVoiceEnded: @json(get_phrase('Conversation ended.')),
            liveVoiceLabel: @json(get_phrase('Voice')),
            liveVoiceConnectingShort: @json(get_phrase('Connecting')),
            liveVoiceListeningShort: @json(get_phrase('Listening')),
            liveVoiceSpeakingShort: @json(get_phrase('Speaking')),
            liveVoiceScreenActive: @json(get_phrase('Screen shared — assistant can see your display')),
            liveVoiceCameraActive: @json(get_phrase('Camera on — assistant can see you')),
            liveVoiceShareHint: @json(get_phrase('Share screen or camera so the voice assistant can see what you see')),
            speakHint: @json(get_phrase('Click the microphone and speak your question.')),
            noReplyToRead: @json(get_phrase('No reply to read yet.')),
        },
        errors: {
            generic: @json(get_phrase('An error occurred. Please try again.')),
            network: @json(get_phrase('Network error. Please try again.')),
            media: @json(get_phrase('Could not access camera or screen. Please allow permission in your browser.')),
            screenUnsupported: @json(get_phrase('Screen sharing is not supported in this browser.')),
            screenCapture: @json(get_phrase('Could not capture the screen. Try sharing the entire screen or another window.')),
            voiceUnsupported: @json(get_phrase('Voice playback is not supported in this browser.')),
            micUnsupported: @json(get_phrase('Speech recognition is not supported in this browser. Use Chrome or Edge.')),
            micDenied: @json(get_phrase('Microphone access denied. Allow the microphone in your browser settings.')),
            micFailed: @json(get_phrase('Could not start the microphone. Please try again.')),
            liveVoiceFailed: @json(get_phrase('Could not start live voice session. Check API configuration and voice assistant access.')),
        },
    };
</script>
