@php
    $coachName = ai_assistant_name();
    $coachBootstrap = $coachBootstrap ?? app(\App\Services\CoachCurriculumService::class)->clientBootstrap(auth()->id());
@endphp
<script>
    window.GeminiAssistantConfig = {
        mode: @json($mode ?? 'widget'),
        defaultOpen: @json(($mode ?? 'widget') !== 'page'),
        assistantName: @json($coachName),
        coachName: @json($coachName),
        defaultTrack: @json($coachBootstrap['default_track'] ?? ''),
        launchBriefing: @json($coachBootstrap['launch_briefing'] ?? ''),
        openingMessage: @json($coachBootstrap['opening_message'] ?? ''),
        stepCard: @json($coachBootstrap['step_card'] ?? null),
        coachQuestion: @json($coachBootstrap['coach_question'] ?? ''),
        initialQuickReplies: @json($coachBootstrap['quick_replies'] ?? []),
        curriculum: @json($coachBootstrap['curriculum'] ?? null),
        initialProgress: @json($coachBootstrap['progress'] ?? null),
        autoStartCoach: true,
        chatUrl: @json(route('ai.assistant.chat')),
        liveTokenUrl: @json(route('ai.assistant.live-token')),
        coachStartUrl: @json(route('ai.assistant.coach.start')),
        coachProgressUrl: @json(route('ai.assistant.coach.progress')),
        labels: {
            welcome: @json($coachBootstrap['launch_briefing'] ?? ('I\'m ' . $coachName . ', your Defrilex Academy coach.')),
            step: @json('Step'),
            ready: @json('Ready to guide you'),
            thinking: @json('Thinking…'),
            liveActive: @json('Live sharing active'),
            screenActive: @json('Screen sharing live'),
            liveOff: @json('Share screen'),
            liveFrame: @json('Live frame will be sent with your message'),
            screenFrame: @json('Screen capture will be sent with your message'),
            snapshotFrame: @json('Snapshot attached to your next message'),
            screenStarted: @json('Screen sharing is on. Reply to your coach or tap Analyze.'),
            cameraStarted: @json('Camera is on. Reply to your coach.'),
            screenStopped: @json('Screen sharing stopped.'),
            screenHint: @json('Tap Screen to share your display.'),
            analyzePrompt: @json('Analyze my screen and help me with what you see.'),
            live: @json('LIVE'),
            liveScreen: @json('SCREEN'),
            liveCamera: @json('CAMERA'),
            listening: @json('Listening…'),
            voiceModeOn: @json('Voice mode on. Speak naturally.'),
            voiceModeOff: @json('Voice mode off.'),
            liveVoiceStart: @json('Start voice coach'),
            liveVoiceConnecting: @json('Connecting to voice coach…'),
            liveVoiceListening: @json('Speak — I\'m listening live.'),
            liveVoiceSpeaking: @json($coachName . ' is speaking…'),
            liveVoiceEnded: @json('Session ended.'),
            liveVoiceLabel: @json('Voice'),
            liveVoiceConnectingShort: @json('Connecting'),
            liveVoiceListeningShort: @json('Listening'),
            liveVoiceSpeakingShort: @json('Speaking'),
            liveVoiceScreenActive: @json('Screen shared — coach can see your display'),
            liveVoiceCameraActive: @json('Camera on — coach can see you'),
            liveVoiceShareHint: @json('Share screen or camera so your coach can guide you'),
            speakHint: @json('Tap the mic and speak.'),
            noReplyToRead: @json('No reply to read yet.'),
            coachSelectTrack: @json('Select a learning path to begin.'),
            coachContinuePrompt: @json('Here\'s my answer:'),
            coachHintPrompt: @json('Give me a short hint for this exercise.'),
            coachExamplePrompt: @json('Show me a practical example for this step.'),
            coachNextPrompt: @json('I\'m ready for the next step.'),
            stepComplete: @json('Step complete!'),
            typeYourAnswer: @json('Type your answer below…'),
            yourTurn: @json('Your turn'),
            coachQuestion: @json('Coach asks'),
            notSurePrompt: @json('I\'m not sure — can you break the question down for me?'),
            answerStarter: @json('My answer: '),
            restartPath: @json('Restart path'),
            curriculum: @json('Curriculum'),
            module: @json('Module'),
            completed: @json('Done'),
            current: @json('Current'),
            pending: @json('Up next'),
        },
        errors: {
            generic: @json('Something went wrong. Please try again.'),
            network: @json('Network error. Please try again.'),
            media: @json('Could not access camera or screen. Allow access in your browser.'),
            screenUnsupported: @json('Screen sharing is not supported in this browser.'),
            screenCapture: @json('Could not capture the screen. Try again.'),
            voiceUnsupported: @json('Text-to-speech is not supported.'),
            micUnsupported: @json('Speech recognition is not supported. Use Chrome or Edge.'),
            micDenied: @json('Microphone denied. Allow it in browser settings.'),
            micFailed: @json('Could not start the microphone.'),
            liveVoiceFailed: @json('Could not start voice coach. Check API configuration.'),
        },
    };
</script>
