<?php

/**
 * Approved external knowledge sources for Defrilex Academy ingestion.
 * Only sources listed here may be fetched automatically.
 */
return [
    'enabled' => env('KNOWLEDGE_INGEST_ENABLED', true),

    // When false, only PDF/HTML sources are ingested (no O*NET, OER Commons, etc.).
    'api_sources_enabled' => env('KNOWLEDGE_API_SOURCES_ENABLED', false),

    // Set false on local Laragon if SSL CA errors occur (imiaweb.org, etc.).
    'verify_ssl' => env('KNOWLEDGE_INGEST_VERIFY_SSL', env('APP_ENV') !== 'local'),

    'user_agent' => env('KNOWLEDGE_INGEST_USER_AGENT', 'DefrilexAcademy-KnowledgeIngest/1.0 (+internal)'),

    'request_timeout' => (int) env('KNOWLEDGE_INGEST_TIMEOUT', 45),

    'rate_limit_ms' => (int) env('KNOWLEDGE_INGEST_RATE_LIMIT_MS', 2000),

    'chunk_size' => (int) env('KNOWLEDGE_CHUNK_SIZE', 1200),

    'chunk_overlap' => (int) env('KNOWLEDGE_CHUNK_OVERLAP', 200),

    'storage_disk' => env('KNOWLEDGE_STORAGE_DISK', 'local'),

    'storage_path' => 'knowledge-sources',

    'onet' => [
        'client' => env('ONET_WS_CLIENT'),
        'base_url' => 'https://services.onetcenter.org/ws',
    ],

    'oer_commons' => [
        'token' => env('OER_COMMONS_API_TOKEN'),
        'base_url' => 'https://www.oercommons.org/api/search',
    ],

    'sources' => [
        'ncihc_standards_of_practice' => [
            'name' => 'NCIHC National Standards of Practice',
            'url' => 'https://www.ncihc.org/assets/documents/publications/NCIHC%20National%20Standards%20of%20Practice.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['interpreters'],
            'priority' => 'high',
            'citation' => 'National Council on Interpreting in Health Care (NCIHC)',
        ],
        'ncihc_code_of_ethics' => [
            'name' => 'NCIHC National Code of Ethics',
            'url' => 'https://www.ncihc.org/assets/documents/publications/NCIHC%20National%20Code%20of%20Ethics.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['interpreters'],
            'priority' => 'high',
            'citation' => 'National Council on Interpreting in Health Care (NCIHC)',
        ],
        'najit_code_of_ethics' => [
            'name' => 'NAJIT Code of Ethics',
            'url' => 'https://najit.org/wp-content/uploads/2016/09/NAJITCodeofEthicsFINAL.pdf',
            'type' => 'pdf',
            'license' => 'free_public',
            'commercial_use' => true,
            'departments' => ['interpreters', 'legal'],
            'priority' => 'high',
            'citation' => 'National Association of Judiciary Interpreters and Translators (NAJIT)',
        ],
        'chia_standards_page' => [
            'name' => 'CHIA Healthcare Interpreter Standards',
            'url' => 'https://www.chiaonline.org/CHIA-Standards',
            'type' => 'html',
            'license' => 'free_public',
            'commercial_use' => true,
            'departments' => ['interpreters'],
            'priority' => 'high',
            'citation' => 'California Healthcare Interpreting Association (CHIA)',
        ],
        'imia_standards' => [
            'name' => 'IMIA Medical Interpreting Standards',
            'url' => 'http://www.imiaweb.org/standards/',
            'type' => 'html',
            'license' => 'free_public',
            'commercial_use' => true,
            'departments' => ['interpreters'],
            'priority' => 'high',
            'citation' => 'International Medical Interpreters Association (IMIA)',
        ],
        'atd_capability_model' => [
            'name' => 'ATD Talent Development Capability Model',
            'url' => 'https://assets.td.org/m/7a140329009da30d/original/1573037137_CapMod-Template-Tool-BrandUpdate-2025.pdf',
            'type' => 'pdf',
            'license' => 'atd_reference',
            'commercial_use' => true,
            'departments' => ['learning_development', 'qa', 'management'],
            'priority' => 'high',
            'citation' => 'Association for Talent Development (ATD)',
        ],
        'kirkpatrick_model_intro' => [
            'name' => 'Kirkpatrick New World Model Introduction',
            'url' => 'https://www.kirkpatrickpartners.com/wp-content/uploads/2021/11/Introduction-to-The-New-World-Kirkpatrick%C2%AE-Model.pdf',
            'type' => 'pdf',
            'license' => 'kirkpatrick_reference',
            'commercial_use' => true,
            'departments' => ['learning_development', 'qa'],
            'priority' => 'high',
            'citation' => 'Kirkpatrick Partners',
        ],
        'nist_ai_rmf' => [
            'name' => 'NIST AI Risk Management Framework',
            'url' => 'https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['qa', 'management'],
            'priority' => 'medium',
            'citation' => 'National Institute of Standards and Technology (NIST)',
        ],
        'osha_worker_rights' => [
            'name' => 'OSHA Worker Rights and Employer Responsibilities',
            'url' => 'https://www.osha.gov/sites/default/files/publications/osha3021.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['operations', 'customer_service', 'management'],
            'priority' => 'low',
            'citation' => 'Occupational Safety and Health Administration (OSHA)',
        ],
        'chia_standards_pdf' => [
            'name' => 'CHIA California Standards for Healthcare Interpreters (PDF)',
            'url' => 'https://www.migrationpolicy.org/sites/default/files/language_portal/ca_standards_healthcare_interpreters_0.pdf',
            'type' => 'pdf',
            'license' => 'free_public',
            'commercial_use' => true,
            'departments' => ['interpreters'],
            'priority' => 'high',
            'citation' => 'California Healthcare Interpreting Association (CHIA)',
        ],
        'publicservice_lsp_guide' => [
            'name' => 'NZ Public Service Leadership Success Profile (Expanded Guide)',
            'url' => 'https://www.publicservice.govt.nz/assets/DirectoryFile/LSP_Expanded_guide_July_2016.pdf',
            'type' => 'pdf',
            'license' => 'free_public',
            'commercial_use' => true,
            'departments' => ['management', 'learning_development'],
            'priority' => 'high',
            'citation' => 'Te Kawa Mataaho Public Service Commission (New Zealand)',
        ],
        'lacounty_customer_service' => [
            'name' => 'LA County Customer Service Information Guide',
            'url' => 'https://hr.lacounty.gov/wp-content/uploads/2019/11/CustomerServiceGuide20091208.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['customer_service'],
            'priority' => 'high',
            'citation' => 'County of Los Angeles Department of Human Resources',
        ],
        'dc_customer_service_excellence' => [
            'name' => 'DC Customer Service Excellence Participants Guide',
            'url' => 'https://dccouncil.gov/wp-content/uploads/2017/05/CustomerServiceExcellenceParticipantsGuide2.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['customer_service'],
            'priority' => 'medium',
            'citation' => 'Government of the District of Columbia',
        ],
        'sbtdc_digital_marketing' => [
            'name' => 'SBTDC Digital Marketing Guide',
            'url' => 'https://sbtdc.org/wp-content/uploads/2022/09/digitalmarketingguide.pdf',
            'type' => 'pdf',
            'license' => 'free_public',
            'commercial_use' => true,
            'departments' => ['marketing', 'sales'],
            'priority' => 'high',
            'citation' => 'North Carolina Small Business and Technology Development Center (SBTDC)',
        ],
        'ftc_internet_marketing_rules' => [
            'name' => 'FTC Advertising and Marketing on the Internet: Rules of the Road',
            'url' => 'https://www.ftc.gov/system/files/ftc_gov/pdf/bus28-rulesroad-2024_508.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['marketing'],
            'priority' => 'high',
            'citation' => 'Federal Trade Commission (FTC)',
        ],
        'eric_sales_fundamentals' => [
            'name' => 'ERIC Sales Fundamentals Curriculum Guide',
            'url' => 'https://files.eric.ed.gov/fulltext/ED312443.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['sales', 'customer_service'],
            'priority' => 'high',
            'citation' => 'U.S. Department of Education / ERIC (North Carolina DPI)',
        ],
        'najit_modes_interpreting' => [
            'name' => 'NAJIT Modes of Interpreting in Legal Settings',
            'url' => 'https://najit.org/wp-content/uploads/2016/09/Modes_of_Interpreting200609.pdf',
            'type' => 'pdf',
            'license' => 'free_public',
            'commercial_use' => true,
            'departments' => ['interpreters', 'legal'],
            'priority' => 'high',
            'citation' => 'National Association of Judiciary Interpreters and Translators (NAJIT)',
        ],
        'najit_summary_interpreting' => [
            'name' => 'NAJIT Summary Interpreting in Legal Settings (Position Paper)',
            'url' => 'https://najit.org/wp-content/uploads/2016/09/SummaryInterpreting200609.pdf',
            'type' => 'pdf',
            'license' => 'free_public',
            'commercial_use' => true,
            'departments' => ['interpreters', 'legal'],
            'priority' => 'high',
            'citation' => 'National Association of Judiciary Interpreters and Translators (NAJIT)',
        ],
        'najit_certification_tiers' => [
            'name' => 'NAJIT Interpreter Certification Tiers White Paper',
            'url' => 'https://najit.org/wp-content/uploads/2021/12/Interpreter-Certification-Tiers.pdf',
            'type' => 'pdf',
            'license' => 'free_public',
            'commercial_use' => true,
            'departments' => ['interpreters', 'legal', 'qa'],
            'priority' => 'medium',
            'citation' => 'National Association of Judiciary Interpreters and Translators (NAJIT)',
        ],
        'ny_dol_customer_service_outline' => [
            'name' => 'NY DOL Customer Service Representative Apprenticeship Outline',
            'url' => 'https://dol.ny.gov/system/files/documents/2024/10/customer_service_representative_73-629_09.23.2024.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['customer_service', 'operations'],
            'priority' => 'high',
            'citation' => 'New York State Department of Labor',
        ],
        'miamidade_service_excellence' => [
            'name' => 'Miami-Dade County Service Excellence Workshop',
            'url' => 'https://www.miamidade.gov/resources/human-resources/documents/elearning-service-excellence.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['customer_service', 'management'],
            'priority' => 'high',
            'citation' => 'Miami-Dade County Human Resources',
        ],
        'panynj_coaching_playbook' => [
            'name' => 'Port Authority WE SOAR Performance Coaching Playbook',
            'url' => 'https://www.panynj.gov/content/dam/wesoar/pdf/WE%20SOAR%20Performance%20Coaching%20Playbook%20V2.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['management', 'learning_development', 'qa'],
            'priority' => 'high',
            'citation' => 'Port Authority of New York and New Jersey',
        ],
        'chcoc_leadership_engagement' => [
            'name' => 'OPM CHCOC Annual Report — Employee Engagement & Leadership',
            'url' => 'https://www.opm.gov/chcoc/annual-reports/2014-2016-annual-report.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['management', 'learning_development'],
            'priority' => 'high',
            'citation' => 'U.S. Office of Personnel Management / CHCOC',
        ],
        'ohio_motivation_leadership' => [
            'name' => 'Ohio Motivation-Driven Leadership Handbook',
            'url' => 'https://dam.assets.ohio.gov/image/upload/jfs.ohio.gov/owd/CCMEP/docs/Motivation-DrivenLeadershipHandbook.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['management', 'learning_development'],
            'priority' => 'medium',
            'citation' => 'State of Ohio Department of Job and Family Services',
        ],
        'eric_managerial_coaching' => [
            'name' => 'ERIC Managerial Coaching and Employee Development',
            'url' => 'https://files.eric.ed.gov/fulltext/ED501641.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['management', 'learning_development', 'qa'],
            'priority' => 'medium',
            'citation' => 'U.S. Department of Education / ERIC',
        ],
        'usps_sales_associate_workbook' => [
            'name' => 'USPS Sales and Services Associate Workbook',
            'url' => 'https://www.prc.gov/docs/28/28700/7610040008860.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['sales', 'customer_service'],
            'priority' => 'medium',
            'citation' => 'United States Postal Service',
        ],
        'usps_sales_facilitator_guide' => [
            'name' => 'USPS Sales and Services Associate Facilitator Guide',
            'url' => 'https://www.prc.gov/docs/28/28700/7610040008859.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['sales', 'customer_service', 'learning_development'],
            'priority' => 'medium',
            'citation' => 'United States Postal Service',
        ],
        'ftc_influencer_disclosures' => [
            'name' => 'FTC Disclosures 101 for Social Media Influencers',
            'url' => 'https://www.ftc.gov/system/files/documents/plain-language/1001a-influencer-guide-508_1.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['marketing'],
            'priority' => 'high',
            'citation' => 'Federal Trade Commission (FTC)',
        ],
        'ftc_endorsement_guides' => [
            'name' => 'FTC Guides on Endorsements and Testimonials in Advertising',
            'url' => 'https://search.ftc.gov/sites/default/files/attachments/press-releases/ftc-publishes-final-guides-governing-endorsements-testimonials/091005revisedendorsementguides.pdf',
            'type' => 'pdf',
            'license' => 'public_domain',
            'commercial_use' => true,
            'departments' => ['marketing', 'sales'],
            'priority' => 'high',
            'citation' => 'Federal Trade Commission (FTC)',
        ],
        'onet_interpreters_translators' => [
            'name' => 'O*NET Interpreters and Translators',
            'url' => 'https://services.onetcenter.org/ws/online/occupations/27-3091.00/summary',
            'type' => 'onet',
            'requires_api' => true,
            'onet_soc' => '27-3091.00',
            'license' => 'onet_attribution',
            'commercial_use' => true,
            'departments' => ['interpreters'],
            'priority' => 'high',
            'citation' => 'O*NET OnLine, sponsored by U.S. Department of Labor',
        ],
        'onet_customer_service' => [
            'name' => 'O*NET Customer Service Representatives',
            'url' => 'https://services.onetcenter.org/ws/online/occupations/43-4051.00/summary',
            'type' => 'onet',
            'requires_api' => true,
            'onet_soc' => '43-4051.00',
            'license' => 'onet_attribution',
            'commercial_use' => true,
            'departments' => ['customer_service'],
            'priority' => 'high',
            'citation' => 'O*NET OnLine, sponsored by U.S. Department of Labor',
        ],
        'onet_sales_reps' => [
            'name' => 'O*NET Sales Representatives',
            'url' => 'https://services.onetcenter.org/ws/online/occupations/41-4011.00/summary',
            'type' => 'onet',
            'requires_api' => true,
            'onet_soc' => '41-4011.00',
            'license' => 'onet_attribution',
            'commercial_use' => true,
            'departments' => ['sales'],
            'priority' => 'high',
            'citation' => 'O*NET OnLine, sponsored by U.S. Department of Labor',
        ],
        'onet_marketing_managers' => [
            'name' => 'O*NET Marketing Managers',
            'url' => 'https://services.onetcenter.org/ws/online/occupations/11-2021.00/summary',
            'type' => 'onet',
            'requires_api' => true,
            'onet_soc' => '11-2021.00',
            'license' => 'onet_attribution',
            'commercial_use' => true,
            'departments' => ['marketing', 'management'],
            'priority' => 'medium',
            'citation' => 'O*NET OnLine, sponsored by U.S. Department of Labor',
        ],
        'onet_hr_managers' => [
            'name' => 'O*NET Human Resources Managers',
            'url' => 'https://services.onetcenter.org/ws/online/occupations/11-3121.00/summary',
            'type' => 'onet',
            'requires_api' => true,
            'onet_soc' => '11-3121.00',
            'license' => 'onet_attribution',
            'commercial_use' => true,
            'departments' => ['management', 'hr'],
            'priority' => 'medium',
            'citation' => 'O*NET OnLine, sponsored by U.S. Department of Labor',
        ],
        'onet_training_development' => [
            'name' => 'O*NET Training and Development Specialists',
            'url' => 'https://services.onetcenter.org/ws/online/occupations/13-1151.00/summary',
            'type' => 'onet',
            'requires_api' => true,
            'onet_soc' => '13-1151.00',
            'license' => 'onet_attribution',
            'commercial_use' => true,
            'departments' => ['learning_development', 'qa'],
            'priority' => 'high',
            'citation' => 'O*NET OnLine, sponsored by U.S. Department of Labor',
        ],
        'oer_commons_customer_service' => [
            'name' => 'OER Commons - Customer Service Training',
            'type' => 'oer_commons',
            'requires_api' => true,
            'query' => 'customer service training',
            'license' => 'cc-by',
            'commercial_use' => true,
            'departments' => ['customer_service'],
            'priority' => 'medium',
            'citation' => 'OER Commons (CC-BY filtered)',
        ],
        'oer_commons_sales_training' => [
            'name' => 'OER Commons - Sales Training',
            'type' => 'oer_commons',
            'requires_api' => true,
            'query' => 'sales training B2B',
            'license' => 'cc-by',
            'commercial_use' => true,
            'departments' => ['sales'],
            'priority' => 'medium',
            'citation' => 'OER Commons (CC-BY filtered)',
        ],
    ],
];
